application: appid
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

includes:
- lib/mapreduce/include.yaml

handlers:
- url: /_ah/pipeline.*
  script: pipeline.handlers._APP
  login: admin

- url: /.*
  script: app.app
  secure: always

